"""document table

Revision ID: 339561853752
Revises: f4ac15b6c732
Create Date: 2025-04-20 20:33:58.403779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339561853752'
down_revision = 'f4ac15b6c732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_deposition', sa.DateTime(), nullable=False),
    sa.Column('data', sa.String(length=150), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_deliverable', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_deliverable'], ['Deliverable.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Document')
    # ### end Alembic commands ###
