"""nullable file type

Revision ID: c73a9f63675d
Revises: 339561853752
Create Date: 2025-04-23 15:28:26.073367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c73a9f63675d'
down_revision = '339561853752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Document', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Document', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
