"""dateInterval

Revision ID: e2a6227b0de1
Revises: f7a6eac0696f
Create Date: 2025-04-19 19:10:37.480063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2a6227b0de1'
down_revision = 'f7a6eac0696f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
