"""delivrables table

Revision ID: f4ac15b6c732
Revises: e2a6227b0de1
Create Date: 2025-04-20 19:44:52.579901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ac15b6c732'
down_revision = 'e2a6227b0de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deliverable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_closure', sa.DateTime(), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Deliverable')
    # ### end Alembic commands ###
