"""add table work, project

Revision ID: f7a6eac0696f
Revises: 4fc222119fcd
Create Date: 2025-04-19 17:08:44.640787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a6eac0696f'
down_revision = '4fc222119fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'DISMANTLED', name='projectstatus'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('id_creator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creator'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Work',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['Project.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_project')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Work')
    op.drop_table('Project')
    # ### end Alembic commands ###
